language: node_js
node_js:
- '0.12'
- '0.10'
install:
- npm install -g grunt-cli
- npm install
script: grunt travis
addons:
  sauce_connect:
    username: saucelabs_esky
    access_key:
      secure: AGufhH2XdB2jLnTqU4uoUTPCNEjMhNzvvqL9FhE9XJnOizQf5CkGPyF/xoePQxvGbtbthTJJ2iL+Pcq2G+r06zoWkQ6oM18cGuPjHW0pU3i/cyeycyThTH3eOvYA1FAyQ9VOqnfFhQx7aVVfLhqTjPpNuk/xgO+igqAO3dZFN/E=
  code_climate:
    repo_token:
      secure: ZFFqkP1PCspj3UGAEuCEkldP0Jy70SZLS2tsBQwBVuMHIK9gcsknXoCyo47kpUQo2N1HD9XQoWlenY/0nDtyGooukfGp0GJAt92wC04/wIquA54UaC7Mtlz8qJsVFEqDlfe5P3DyMfvSfbsbrL+/GGOoNS7eKPNKwRjNPr1MFx0=
deploy:
  provider: npm
  email:
    secure: YBkNVD3O7iUtEWoQr5ySwMZnBb8dpBm784MuuhKHbYIiYSgrSlkI4QSlTFosKcXX9s7T863GThS5NvzZbHqNRhGkCPqIpHalw/vzlm58NtlaMXmiSID69GoUc1r5UbYIdoReUjUGzWH1JfVCgSOOmKCScoRXAQdQJd7RbgK8hTc=
  api_key:
    secure: DY5jPrmjzeAGgmv5rk2OlVhQjIptJaCvyfcfTxQzp4y1wE6j2zmSG4xkkHIcrsonRyyW3RRI/IuBZwdwex5OfuJ2qOd3UCJYTr+lVg3QubRBj4XaxloQVoMuYMIclngYZ5Kvnx41NwT1KCu7pTEZdn0VBOKgQRZMafSKBDyIhZU=
  on:
    node: 0.12
    tags: true
    branch: master
    repo: eskypl/glide-templates
after_script:
  - codeclimate < coverage/lcov.info
