language: node_js
node_js:
- '0.12'
- '0.10'
install:
- npm install -g grunt-cli
- npm install
script: grunt travis
env:
  global:
  - secure: gcwGJYJdGIcsYydabV7nvh4Z3aHCWSb6Bs1DvNGsCTDhw/a3uks2m0gUNzEQFP0pE5BnOT5svvHsj3K56G4Dy77UXsasoU/FpduZ5PGPdUZNdu5GSAV7SXv7uoU9nlJfwSOhb99ddfdLDaHfae8hA50d6ZtXA4h0Wpyk9G4OW5k=
  - secure: ZPI5ruBs1hZA3tB2qlsvpwxzOP4FBVNpKh/2BQzM7euO0Ut38IABOiBMZjPFP3z/6eG8h0Wq8PPUmL+TuTC7KIy/sPrZUmQ+EYTBIaDx7UTCarSXl6URZezJeqUcFTUBY6NI7fMDeiIX5p7NzDCSL2tVM2AejVtqOc0DU086OmY=
addons:
  sauce_connect: true
  code_climate:
    repo_token:
      secure: ZFFqkP1PCspj3UGAEuCEkldP0Jy70SZLS2tsBQwBVuMHIK9gcsknXoCyo47kpUQo2N1HD9XQoWlenY/0nDtyGooukfGp0GJAt92wC04/wIquA54UaC7Mtlz8qJsVFEqDlfe5P3DyMfvSfbsbrL+/GGOoNS7eKPNKwRjNPr1MFx0=
deploy:
  provider: npm
  email:
    secure: YBkNVD3O7iUtEWoQr5ySwMZnBb8dpBm784MuuhKHbYIiYSgrSlkI4QSlTFosKcXX9s7T863GThS5NvzZbHqNRhGkCPqIpHalw/vzlm58NtlaMXmiSID69GoUc1r5UbYIdoReUjUGzWH1JfVCgSOOmKCScoRXAQdQJd7RbgK8hTc=
  api_key:
    secure: DY5jPrmjzeAGgmv5rk2OlVhQjIptJaCvyfcfTxQzp4y1wE6j2zmSG4xkkHIcrsonRyyW3RRI/IuBZwdwex5OfuJ2qOd3UCJYTr+lVg3QubRBj4XaxloQVoMuYMIclngYZ5Kvnx41NwT1KCu7pTEZdn0VBOKgQRZMafSKBDyIhZU=
  on:
    node: 0.12
    tags: true
    branch: master
    repo: eskypl/glide-templates
after_script:
  - cat coverage/lcov.info | codeclimate
