language: node_js
node_js:
- '0.12'
- '0.10'
install:
- npm install -g grunt-cli codeclimate-test-reporter
- npm install
script: grunt travis
env:
  global:
  - secure: fqyrcxEocFNipjhg5qljThprOlhGwpnhicKXFj3j4bzAHuizMjLA9EVEmrzrP4cTWmUa7TYD5uP3O+Um6nxvzKLmnepTjgUOJURnl/IYW1Q6vqucUYw8sALhLctnVwDt8kwuDdiOYngsbBL7NTfSa1VhvIjmAM0EF9m82gnYHeg=
  - secure: dKa1fbjraoLQb9f8kYt42DzPLY2A9jzDfxbLuHv2FakxWZMMucNKu1HOSTNg/m4tqmzNMkH13livS7CYk6mcxjwYTsTscf+c5Bp2/CBN+FXEP8PAreSIflEPekQtKI93b3Mgm1OVTuxM6pldjbqdT0z/OS12c/wW5PxeptrR2Cc=
addons:
  sauce_connect: true
  code_climate:
    repo_token:
      secure: ZFFqkP1PCspj3UGAEuCEkldP0Jy70SZLS2tsBQwBVuMHIK9gcsknXoCyo47kpUQo2N1HD9XQoWlenY/0nDtyGooukfGp0GJAt92wC04/wIquA54UaC7Mtlz8qJsVFEqDlfe5P3DyMfvSfbsbrL+/GGOoNS7eKPNKwRjNPr1MFx0=
deploy:
  provider: npm
  email:
    secure: YBkNVD3O7iUtEWoQr5ySwMZnBb8dpBm784MuuhKHbYIiYSgrSlkI4QSlTFosKcXX9s7T863GThS5NvzZbHqNRhGkCPqIpHalw/vzlm58NtlaMXmiSID69GoUc1r5UbYIdoReUjUGzWH1JfVCgSOOmKCScoRXAQdQJd7RbgK8hTc=
  api_key:
    secure: DY5jPrmjzeAGgmv5rk2OlVhQjIptJaCvyfcfTxQzp4y1wE6j2zmSG4xkkHIcrsonRyyW3RRI/IuBZwdwex5OfuJ2qOd3UCJYTr+lVg3QubRBj4XaxloQVoMuYMIclngYZ5Kvnx41NwT1KCu7pTEZdn0VBOKgQRZMafSKBDyIhZU=
  on:
    node: 0.12
    tags: true
    branch: master
    repo: eskypl/glide-templates
after_script:
- codeclimate < coverage/lcov.info
